# Generated by Django 5.1.4 on 2025-01-05 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctors_experience_years_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='notes_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='notes_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='staff_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='staff_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='status_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='status_ru',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='department',
            name='location_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='location_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='doctor_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='doctor_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='patient_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='patient_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_en',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_ru',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalrecord', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalrecord', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientProfile', to='hospital.profile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientProfile', to='hospital.profile'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='dosage_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='dosage_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='medication_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='medication_ru',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='patient_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='patient_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital.patientprofile'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='staff_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='staff_id_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='hospital.doctors'),
        ),
        migrations.AddField(
            model_name='wards',
            name='capacity_en',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='capacity_ru',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='current_occupancy_en',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='current_occupancy_ru',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='ward_type_en',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='wards',
            name='ward_type_ru',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
