# Generated by Django 5.1.4 on 2025-01-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_prescriptions_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patient_id_en',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='patient_id_ru',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='staff_id_en',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='staff_id_ru',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patient_id_en',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patient_id_ru',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='experience_years_en',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='experience_years_ru',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='doctor_id_en',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='doctor_id_ru',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='patient_id_en',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='patient_id_ru',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_id_en',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_id_ru',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient_id_en',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient_id_ru',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user_ru',
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
