# Generated by Django 5.1.4 on 2025-01-05 12:38

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_prescriptions_patient_id_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='speciality_en',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='speciality_ru',
        ),
        migrations.AddField(
            model_name='wards',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бомбейский фенотип (hh)', 'Бомбейский фенотип (hh)'), ('Золотая кровь (Rh-нулевой)', 'Золотая кровь (Rh-нулевой)'), ('Группа крови О−', 'Группа крови О−'), ('Группа крови О+', 'Группа крови О+'), ('Группа крови А−', 'Группа крови А−'), ('Группа крови А+', 'Группа крови А+'), ('Группа крови Б−', 'Группа крови Б−'), ('Группа крови В+', 'Группа крови В+'), ('Группа крови АБ−', 'Группа крови АБ−'), ('Группа крови АБ+', 'Группа крови АБ+')], default=2, max_length=43),
            preserve_default=False,
        ),
    ]
