# Generated by Django 5.1.4 on 2025-01-05 18:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_speciality_speciality_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status_en',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status_ru',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='ward_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'STANDARD')], default='STANDARD', max_length=10),
        ),
        migrations.AlterField(
            model_name='wards',
            name='ward_type_en',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'STANDARD')], default='STANDARD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='ward_type_ru',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'STANDARD')], default='STANDARD', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Direction_and_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor', models.ManyToManyField(to='hospital.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=32, unique=True)),
                ('hospital_image', models.ImageField(upload_to='hospital_image/')),
                ('address', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('operating_mode', models.CharField(max_length=300)),
                ('chief_physician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors', verbose_name='Главный врач')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Name_and_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='hospital.direction_and_services')),
            ],
        ),
    ]
